<?php 
$app->make("config")->set("Debug.debug", "1");
$app->make("config")->set("default_language.folder_code", "eng");
$app->make("config")->set("default_language.language_code", "1");
$app->make("config")->set("default_language.name", "English");
$app->make("config")->set("Email.client", "123");
$app->make("config")->set("Email.host", "ssl://smtp.gmail.com");
$app->make("config")->set("Email.password", "deepak");
$app->make("config")->set("Email.port", "465");
$app->make("config")->set("Email.timeout", "30");
$app->make("config")->set("Email.username", "deepak.mittal@emizentech.com");
$app->make("config")->set("Reading.date_format", "d-M-Y h:ia");
$app->make("config")->set("Reading.records_per_page", "20");
$app->make("config")->set("Site.address", "Calle Sant Pere n 4 - 2 AT - 08870 SITGES (BARCELONA) - SPAIN");
$app->make("config")->set("Site.administrator_name", "LAST PLACES - Admin");
$app->make("config")->set("Site.contact_email", "contact@lastplaces.com");
$app->make("config")->set("Site.copyright_text", "Copyright © 2019 LAST PLACES. All rights reserved.");
$app->make("config")->set("Site.email", "contact@lastplaces.com");
$app->make("config")->set("Site.fax", "000-000-0000");
$app->make("config")->set("Site.google_analytics_code", "");
$app->make("config")->set("Site.headerimage", "1560435403-HeaderSetting.jpg");
$app->make("config")->set("Site.map", "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2418.7907194875675!2d0.9495223822784421!3d52.68181689148524!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47d9d7c8c3b7d333%3A0xf461a694a70b6139!2sDHCP+counselling+services!5e0!3m2!1sen!2sin!4v1540204443333");
$app->make("config")->set("Site.meta_description", "LAST PLACES");
$app->make("config")->set("Site.meta_keywords", "LAST PLACES");
$app->make("config")->set("Site.name_display_in_emails", "LAST PLACES");
$app->make("config")->set("Site.phone", "+34 935 439 601");
$app->make("config")->set("Site.title", "LAST PLACES");
$app->make("config")->set("Social.facebook", "https://www.facebook.com/Last-Places-2406095742796416");
$app->make("config")->set("Social.instagram", "https://www.instagram.com/last.places");
$app->make("config")->set("Social.linkedin", "");
$app->make("config")->set("Social.pinterest", "http://pinterest.com/lastplaces");
$app->make("config")->set("Social.youtube", "https://www.youtube.com/channel/UC4kN2qmf-Bh5BhUuT8rsOMw");
$app->make("config")->set("test.gplus", "https://plus.google.com/discover");
$app->make("config")->set("test.twitter", "http://twitter.com/lastplaces");
